Hw 1
Mihail-Olegovich/ITMO-MLSD-2024 pull request #1
Opened 2024-11-25 19:03 UTC by Mihail-Olegovich

2024-12-04 14:24 UTC, MakArtKar requested changes
Привет! Все ок, но лучше заполнить README более подробно + добавить quickstart, пока только про настройку ruff и black (пример можешь посмотреть [тут](https://github.com/AshimIsha/ML_sys_design_2024/tree/hw_1))

### Чек-лист проверки выполнения задач

#### 1. Сетап репозитория проекта
- [x] Репозиторий подготовлен для работы:
  - [x] Настроены линтеры и форматеры (ruff, black).  
  - [x] Настроен pre-commit.  
  - [x] Заполнен файл `README.md` с основной информацией о проекте.  

#### 2. Заполнение дизайн-документа
- [x] В репозитории создана папка `docs`.
- [x] В папке `docs` создан файл `ml_system_design_doc.md`.
- [x] В файле `ml_system_design_doc.md` заполнена следующая информация:
  - [x] Зачем идем в разработку продукта?  
  - [x] Бизнес-требования и ограничения.  
  - [x] Что входит в скоуп проекта/итерации, что не входит.  
  - [x] Предпосылки решения.  
  - [x] Постановка задачи.  
  - [x] Блок-схема решения.

2024-12-04 22:22 UTC, danilovsnnv commented
### Чек-лист проверки выполнения задач

#### 1. Сетап репозитория проекта
- [x] Репозиторий подготовлен для работы:
  - [x] Настроены линтеры и форматеры (ruff, black).  
  - [x] Настроен pre-commit.  
  - [x] Заполнен файл `README.md` с основной информацией о проекте.  

#### 2. Заполнение дизайн-документа
- [x] В репозитории создана папка `docs`.
- [x] В папке `docs` создан файл `ml_system_design_doc.md`.
- [x] В файле `ml_system_design_doc.md` заполнена следующая информация:
  - [x] Зачем идем в разработку продукта?  
  - [x] Бизнес-требования и ограничения.  
  - [x] Что входит в скоуп проекта/итерации, что не входит.  
  - [x] Предпосылки решения.  
  - [x] Постановка задачи.  
  - [x] Блок-схема решения.  

### Комментарии

Здорово, что есть описание целевой аудитории и сценариев использования, а также подробно расписаны бизнес требования.

Есть небольшие уточнения:
1) Хотелось бы более подробное `README` репозитория
2) Следует добавить бизнес ограничения в пункт 1.3 (если они, конечно, есть, но зачастую их можно найти)
3) Следует добавить информацию о решаемой задачи с точки зрения ML (суммаризация, генерация или др.)

2024-12-08 18:56 UTC, eelduck commented on pyproject.toml
> +
А где black, ruff в зависимостях?

Хотя бы в dev добавить

`poetry add -G dev ruff black`

2024-12-08 18:56 UTC, eelduck commented on docs/ml_system_design_doc.md
> +
Стоит добавить для контекста пару предложений в самом начале для обывателей - что это за система

2024-12-08 18:56 UTC, eelduck commented on docs/ml_system_design_doc.md
> +3. Сервис обработки запросов должен уметь адаптироваться к контексту разговора, учитывая предыдущие запросы и сопутствующую информацию в течение сессии (Например, когда была предоставлена первая выгр
Поддержку контекста диалога я бы убрал из первой итерации - много сложностей добавляет, что замедлит разработку и получение первой обратной связи хотя бы по простым запросам

2024-12-08 18:56 UTC, eelduck commented on docs/images/query-processing-service-scheme.png
Запрос в БД кто будет делать? Мб добавить сервис, который принимает SQL запрос от LLM и отправляет в БД

Потому что валидатор (LLM) явно такое не сможет

2024-12-09 05:54 UTC, Mihail-Olegovich commented on docs/ml_system_design_doc.md
> +
Согласен, добавил

2024-12-22 08:15 UTC, merged